### ISSUE TITLE
Add validation in API Direct Webhook

### ISSUE THREAD

**Issue by whdalsrnt** [spaceone-dev/plugin-api-direct-mon-webhook#7]

**Comment by jihyungSong** [comment]
Currently, only the key value of string type can be received as the value of additional_info, and an error occurs if a type other than string is provided.

Because additional_info allows the user to freely send information, change the code to convert type to string instead of generating an error

https://github.com/spaceone-dev/plugin-api-direct-mon-webhook/pull/10/commits/822ed8dc4ea62709e223816093d01e95e567a554#diff-4a4a2d419e81f8de4c821d8768324d46096429bf8ffcd3bb1eed58d6bd2725f9R47
